# Generated by Django 2.2.8 on 2019-12-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('article', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
